### ISSUE TITLE
multi split combo permutations

### ISSUE THREAD

**Issue by illmillrig** [blurstudio/Simplex#113]
Hey,  So ran into an interesting splitting issue today, and wanted to get your thoughts on it.  It's a little difficult to describe so here it goes....

there are two shapes and a combo:
```
  shape1_X_Y
  shape2_X_Y

  shape1_X_Y_shape2_X_Y
```
after we split we get 8 sliders, and 4 combos
```
  shape1_L_U
  shape1_L_D
  shape1_R_U
  shape1_R_D
  shape2_L_U
  shape2_L_D
  shape2_R_U
  shape2_R_D

  shape1_L_U_shape2_L_U
  shape1_L_D_shape2_L_D
  shape1_R_U_shape2_R_U
  shape1_R_D_shape2_R_D
```
Let's just look a the Left side for now
```
  shape1_L_U
  shape1_L_D
  shape2_L_U
  shape2_L_D

  shape1_L_U_shape2_L_U
  shape1_L_D_shape2_L_D
```
the combos we got after splitting are not ALL the possible permutations.  these are the possible combos...
```
  shape1_L_U_shape2_L_U
  shape1_L_D_shape2_L_D
  shape1_L_U_shape2_L_D
  shape1_L_D_shape2_L_U
```
there are two permutations we did not get where the L_U is combo'd with the L_D, and these are the combos that we want in this particular case.
```
  shape1_L_U_shape2_L_D
  shape1_L_D_shape2_L_U
```
one shape is being split at the lips vertically, and the other at the nose bridge vertically,  we need the top of the former, and lower of the latter to be the resulting combo

:D

**Comment by tbttfox** [comment]
That can't be done as part of the split algorithm. The splitting algorithm doesn't create combos between the sides of the split. Just like when you split a single `brow_X` shape, you don't expect there to be a `brow_L_R` combo created.

So it sounds like you're going to have to manually separate the U and D shapes and create U/D and D/U combos

**Comment by illmillrig** [comment]
yeah that makes sense.  I suppose only one of those combos would be desirable anyways.  we certainly dont need the bottom of the mouth combo'd with above the nose bridge.  But it is an interesting problem.  Thanks!

**Comment by tbttfox** [comment]
The more I go through this in my head, I don't think it's possible *at all*

Another way to think about this is to *not* just look at the left side in your example, and also consider the right side with the extra possible U/D splits. There are 16 possible combos that could be created ((2<sup>2</sup>)<sup>2</sup>) in that example.
```
LU-LU LU-LD LU-RU LU-RD LD-LU LD-LD LD-RU LD-RD
RU-LU RU-LD RU-RU RU-RD RD-LU RD-LD RD-RU RD-RD
```
Now, if you think of the weightmaps being just a vertical and horizontal line, that splits everything into 4 regions. And at first glance, you could say "4 quadrants, each with 2 options gives 16 possibilities", however we can't use weightmaps that way.  Weightmaps tell us to zero out an entire half of the plane ... So instead, I've got 3 choices per weightmap:
Zero its positive side, Zero its negative side, or just skip that map completely. That gives me 8 possibilities `L, R, U, D, LU, LD, RU, RD`, and there's no good way to map those 16 combos onto those 8 possibilities. (There's also technically the `all/nothing` possibilities, but those are kinda useless.)

Now think of what would happen with 3 splits: There would be (2<sup>3</sup>)<sup>2</sup>=64 combos, but only 26 weightmap possibilities, and there's absolutely no good way to pair those up.

**Comment by illmillrig** [comment]
yeah, I understand. It just feels so doable in our particular case.  the noseWrinkler is being split at the nose bridge, and the funneler is being split between the lips, and there's a combo noseWrinkler_funneler that fixes the lips.  but that means the U of funneler with the D of noseWrinkler is the only desired combo after splitting.  

do you think there could be a way to assign the mapping (if needed) to something custom like this?  so calculate the possible outcomes, and present them to the user for selection? kinda like selecting a falloff on a slider in the context menu
