### ISSUE TITLE
[Bug]: slider not work at mouse middle click -

### ISSUE THREAD

**Issue by chowooseung** [blurstudio/Simplex#123]
### Summary

I'm moving the slider with the middle click of the mouse

plus works as expected but minus doesn't

### Expected Behavior

I thought the slider's value would go down

### Steps to Reproduce Behavior

Create any slider, click the mouse middle, and move

### Environment

window 11
maya 2024.2
maya 2022.5

### Additional Context

https://github.com/blurstudio/Simplex/assets/49386821/78817091-2ca1-42cf-84f4-0498896c060a

It looks like it's working fine on YouTube video. But I don't.
Is this my only problem?

**Comment by tbttfox** [comment]
If you move the mouse faster, does it work?
And which version of simplex did you get?

**Comment by chowooseung** [comment]
If i move the mouse quickly, it sometimes (?) works.

This is the simplex I installed.
https://github.com/blurstudio/Simplex/releases/tag/v3.0.9

**Comment by tbttfox** [comment]
I could've sworn I fixed that exact bug ... and I was right!
Turns out that I fixed it in our local repository, and forgot to push it here to the public one.
This PR should fix it, and I'll have that merged into master in the next day or two
https://github.com/blurstudio/Simplex/pull/127

**Comment by chowooseung** [comment]
Thank you for your confirmation :)

**Comment by tbttfox** [comment]
Ok the fix is merged and released. Should be good to go now.
If not, feel free to reopen this issue.
