### ISSUE TITLE
[Request]:  how to build for centos 7?

### ISSUE THREAD

**Issue by chowooseung** [blurstudio/Simplex#128]
### Description

I am using maya2022 in centos7.
Currently, with version 3.0.9, I get glibc error and it won't load the plug-in. I'm not familiar with it, but this seems to be related to the version of the operating system. Could you please tell me the build process for using centos7?

I tried to modify the main.yml file, but it didn't work out.

**Comment by tbttfox** [comment]
You'll have to compile it locally, which means installing any required dependencies, and running the `Configure Cmake` and `Build` steps from the yml directly on your machine, and figuring out the proper way to change those commands to make it work.  

Hopefully you'll just have to fill in the variables, and remove the devkit base flag so it finds your installed maya.
And really, there's not much more help I can give.
